### ISSUE TITLE
spikes combined with blanks

### ISSUE THREAD

**Issue by tmwood-usgs** [USGS-R/WQ-Review#102]
I am using the blankSummary function, and the summary is interpreting spikes as blanks. My spikes are coded with sample type (1) and my blanks are coded with sample type (2). The medium code on the spikes is WSQ, and the medium code on the blanks is OAQ.

**Comment by tjmills** [comment]
I will take a look, could you send me the station number and NWIS host for that issue?

**Comment by tmwood-usgs** [comment]
Hi,

I'm sending you the R script. It isn't a single site, it's many.

I came in this morning and looked at it again, and I see things somewhat
differently. Many of the detects are because the DL changed through time.
But if you look at the median and max detects, those are based on spiked
samples. It appears to me now that what the program is keying on is the
medium code- those spiked samples it is picking up on were in blank water,
so the medium code was OAQ.

The other thing I don't understand is how to use the ouput of readNWISodbc
in the other functions that require a qw.data object class. The output of
readNWISodbc is a list of 2 data frames. I have tried using the list, and
the two data frames independently, in other functions, and no luck. I also
want to use this output in the censored data routines in package USGSwsQW,
which also require the qw.data object class. No luck with that either.

As an aside, if I can get these problems figured out, is there a way to
combine the readNWISodbc output from OR and CA into one dataset for the
purpose of reporting and analysis with these scripts?

-Tammy

Tamara Wood
Hydrologist
USGS Oregon Water Science Center
2130 SW 5th Ave.
Portland, OR 97201

**Comment by tjmills** [comment]
OK I will watch for those. And yes the blankSummary is not subsetting on sample type code. This is a bug and has now been fixed. Once I look at the rest of the issues I will update on github

**Comment by tjmills** [comment]
Also, when I get those siteIDs and NWIS hosts I will put together an example script that pulls data and runs it through some other functions.

Just out of curiosity, why aren't you using the GUI? Personally, I use the GUI for my work unless I have some reason to run things in batch or in an automated fashion. 

These are great comments that are catching a number of issues. Not many people have used the R package outside of the GUI environment.

**Comment by tmwood-usgs** [comment]
I attached the script, which has the site IDs and the NWIS hosts- did you
get it? If not, I'm attaching again.

I don't usually use a GUI because I always want to do things a little bit
custom. In my case, I need to pull sites from various years and various
NWIS hosts. I wanted to do things outside of the GUI because I have more
control.

Tamara Wood
Hydrologist
USGS Oregon Water Science Center
2130 SW 5th Ave.
Portland, OR 97201

**Comment by tjmills** [comment]
Great just curious, I wanted to see if there was something about it that was not working for you that I could work on.

I emailed about the files, Thanks!
