### ISSUE TITLE
Plot blank timeseries by parameter group

### ISSUE THREAD

**Issue by tsmck** [USGS-R/WQ-Review#109]
It would be helpful to view Blank timeseries plots by parameter groupings, rather than clicking through individual parameters.  I would like to see at a glance if I have a problem with a type of blank.  
Thanks!

**Comment by tjmills** [comment]
Sure, you would like this by NWIS groups? e.g. Cations

**Comment by tsmck** [comment]
I was thinking of the NWIS parameter groupings:
Information
Physical
Radiochemical
Inorganics, Major, Non-metals
Sediment
Organics, other
Biological
Nutrient
Inorganics, Minor, Non-metals
Inorganics, Major, Metals
Inorganics, Minor, Metals
Stable Isotopes
Organics, pesticide
Organics, PCBs
Microbiological
Toxicity

This would be great.  Thanks!

Tim

On Mon, Jun 13, 2016 at 11:06 AM, T. Joe Mills notifications@github.com
wrote:

> Sure, you would like this by NWIS groups? e.g. Cations
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/USGS-R/WQ-Review/issues/109#issuecomment-225644847,
> or mute the thread
> https://github.com/notifications/unsubscribe/AS_a5D2zKLtryj_yT6KO17_4YdYm2tSLks5qLY38gaJpZM4I0iK9
> .

## 

*Tim McKinney *
U.S. Geological Survey
Utah Water Science Center
801-908-5060
tmckinney@usgs.gov

**Comment by tjmills** [comment]
Blank timeseries has been removed in 2.0

Will re-open this issue if functionality still needed in 2.0
