### ISSUE TITLE
Facet multi-site option plot order should match order placed in Station field

### ISSUE THREAD

**Issue by psolberg-usgs** [USGS-R/WQ-Review#120]
It seems to be in alphabetic order, possibly? Its natural for people to expect upstream sites on the left and downstream on the right, if that makes sense. It doesn't seem to matter which order I put the sites in the station field. They are output in the same order (possibly alphabetic). 

Enhancement for sure. 

http://screencast.com/t/qJtRmJ4LkA

**Comment by tjmills** [comment]
Sites are ordered according to their factor level, which is probably alphabetical since they are treated as characters.

I will see if I am able to order them according to user input, but may be difficult

**Comment by tjmills** [comment]
Won't do, likely not going to be a major use-case in the new 2.0

Will re-open if needed
