### ISSUE TITLE
Issue with flipDQI command

### ISSUE THREAD

**Issue by cjhoard** [USGS-R/WQ-Review#132]
I am not able to get the flipDQI function to work for creating a batch file of DQI codes to enter into the database.  Is this functionality something that is still in progress or am I just doing something wrong?  An example and resulting error(s) are included for reference.  There are two error messages that I have received after trying the command on different occasions.

flipDQI('04043237','01300628_01','00608',"R",DSN = "NWISMI", env.db = "01", qa.db = "02", keepRecordNo = FALSE)

error #1
Error in flipDQI("04043237", "01300628_01", "00608", "R", DSN = "NWISMI",  : 
  unused arguments ("04043237", "01300628_01", "00608", "R", DSN = "NWISMI", env.db = "01", qa.db = "02", keepRecordNo = FALSE)

error #2 
Error: could not find function "flipDQI"

**Comment by tjmills** [comment]
Whoops! I did not mean for the function to be exported and made available. This is still a work in progress

**Comment by tjmills** [comment]
Ah I see, it was not made available, but the documentation for it was. Thanks for the issue report

**Comment by tjmills** [comment]
When I make it available, you also have some issues with how you are calling the function. It should be like this:

```
STAIDS <- c("04043237")
records <- c("01300628_01")
parameters <- c("00608")
dqiCodes <- c("R")

flipDQI(STAIDS = STAIDS,
        records = records,
        parameter = parameters,
        dqiCodes = dqiCodes,
        DSN = "NWISMI",
        env.db = "01",
        qa.db = "02",
        keepRecordNo = FALSE)
```

The STAIDS, records, parameters, and dqiCodes arguments need to be vectors

**Comment by cjhoard** [comment]
Cool thanks for clarifying and apologies for jumping the gun on that.  It looks pretty promising for saving some time in creating those batch files.  Thanks for the quick response and for all your work on this code. It is a real benefit to the review process.

**Comment by cjhoard** [comment]
Sorry didn't mean to close this.

**Comment by tjmills** [comment]
@cjhoard 

Checkout this new experimental version that allows for changing DQI codes via batch files
BE CAREFUL! This is in early testing, do not push in the files without verify they are OK


[WQReview 2.0](https://github.com/tmills-usgs/WQ-Review_refactor)
