### ISSUE TITLE
Site not found

### ISSUE THREAD

**Issue by landrade-yuma** [USGS-R/WQ-Review#135]
Hello,

I can't seem to find any data for site 09427520 in server nwisaz database 01 QA database 09.

Thanks

**Comment by tjmills** [comment]
There is no QA data collected at that site in the last 10 years, which caused the function to throw an error that there is no data at all, when it should just throw a warning that there is no QA data and continue onward with the rest of the functionality minus any QA data checks.

This has been fixed and will be available for download by early next week
