### ISSUE TITLE
First basic data import

### ISSUE THREAD

**Issue by bmccarthyqw** [USGS-R/WQ-Review#141]
I am new to using WQ-Review, and trying to do a basic data import according to the instructions provided in the vignette. I have a connection to the DSN, which my IT admin helped set up. As far as we can tell, it is set up correctly. 

https://github.com/USGS-R/WQ-Review/blob/master/vignettes/WQReviewGUI.Rmd#a-basic-data-import 

I am trying to pull all of the parameter codes for a site where I know that the data are approved and uploaded. I've tried both doing it by selecting all parameter groups, as well as by using parameter codes that I know we have data for. 

I get different error messages when running this, sometimes I get : 
"Problem with data import, please check import criteria"
"No samples exist in your local NWIS database for the date range specified, check data criteria"

Other times I get: 
"Problem with data import, please check import criteria"
"Incorrect database number entered for qa.db"

Attached is a screenshot of my QW-Review GUI.

![qwreview](https://cloud.githubusercontent.com/assets/26258536/23673479/7167c8b4-0340-11e7-8c24-0f0a44aaedd0.PNG)

**Comment by tjmills** [comment]
I am in the field this week but I can help trouble shoot next week when I return. The most likely cause is that your data are not stored in the database numbers you specified. Are you sure they are in 01 and 02?

**Comment by bmccarthyqw** [comment]
Thank you for your response, I'm not entirely sure they are in there. Is there a quick way for me to check? I just went with the defaults.

**Comment by tjmills** [comment]
So the database numbers vary center to center so you will need to check with your DBA as to where your data are. The majority of centers have 01 and 02 but MANY do not use those. Maybe fire up qwdata and see what it says at the top of the home menu. I think it shows the database number there

**Comment by tjmills** [comment]
Also thanks for using the GitHub issues!

**Comment by bmccarthyqw** [comment]
I just switched it to 01 and 01, and it worked. Thank you for your time!
