### ISSUE TITLE
Reps and blanks do not show up in unnaproved data tab

### ISSUE THREAD

**Issue by tjmills** [USGS-R/WQ-Review#145]

**Comment by tjmills** [comment]
This pertains to the dev branch

**Comment by cpenn-usgs** [comment]
issue is in `returnAll` from `historicCheck`. Fixed `flaggedSamples` to truly include all if `returnAll = TRUE`, and updated shiny `server_reports` to return all then subset only unapproved samples and any flags. Next PR will close.
