### ISSUE TITLE
Install instruction improvements

### ISSUE THREAD

**Issue by ghost** [USGS-R/WQ-Review#17]
Your 'Installation for R Users' says to start with  > library(devtools)
but that triggers an error to first download and install Rtools (can't be done from the packages menu).  I suspect that is just the start of a dependency cascade of other libraries to be installed. 

![image](https://cloud.githubusercontent.com/assets/14081012/9667262/d48d0472-5248-11e5-9c56-2b26901abc8f.png)

Please have someone with a fresh install of R test the instructions, someone who is not a developer and may be missing some components that are taken for granted, and then revise your pre-installation requirements. 

There is also no comment about whether someone with R can also install the stand-alone version without causing problems.

Thanks.

**Comment by tjmills** [comment]
The stand alone version will not interfere with the R version, and vice versa.

The installation instructions have been updated.
Thanks for the feedback!

**Comment by ghost** [comment]
Joe, Thanks.
I will check it out tomorrow or Monday.

-=Steve

Steve Tessler, PhD
Ecologist / Data Manager
stessler@usgs.gov, USGS Lawrenceville, NJ

# Work Cell (preferred) 609-203-9358, NJ Office 609-771-3965

USGS - NJ Water Science Center http://nj.usgs.gov/
