### ISSUE TITLE
Issues retrieving data from sites containing different agency codes 

### ISSUE THREAD

**Issue by ehermosillo** [USGS-R/WQ-Review#170]
I am having issues retrieving data, it won't retrieve data at all and give me the errors below, when I add a Site number that contains a different agency code aside from the USGS agency code. Only USGS agancy coded site numbers will work.

Errors:
[1] "Problem with data import, please check import criteria"
[1] "ODBC message: Site does not exist in environmantal or QA database sitefile, check site number

**Comment by ehermosillo** [comment]
![capture](https://user-images.githubusercontent.com/13244098/50185857-38c1e980-02d6-11e9-843b-1b2cafe0f68a.PNG)

**Comment by cpenn-usgs** [comment]
To import from sites with non-USGS agency codes, append the agency code and a dash before the site number. Example: USEPA-333330112164801

This documentation is in the R package help file for `readNWISodbc`, but needs to be added to the WQReview 2.0 GUI User Guide. I'll keep this Issue open until that change is made.

**Comment by ehermosillo** [comment]
@cpenn-usgs Thank you so much, Colin! It worked :)

**Comment by cpenn-usgs** [comment]
closed by PR #175. Now added clarification to the [User Guide](https://github.com/USGS-R/WQ-Review/blob/master/vignettes/WQReviewGUI2.md) on how to get sites with different agency codes
