### ISSUE TITLE
Multiple User Data Sources

### ISSUE THREAD

**Issue by ehermosillo** [USGS-R/WQ-Review#178]
Hello. I am from the AZWSC and I am reviewing data for the COWSC. Can I retrieve CO data by adding the "nwisco" TNS Service name and Data Source Name under the Oracle ODBC Driver Configuration? Can I have multiple NWIS servers under the ODBC Data Sources? I've added the nwisco TNS Service name to the odbc data source, but I still can't retrieve any data on WQReview 2.0. 

Thank you for your help on this!

**Comment by cpenn-usgs** [comment]
You can add multiple NWIS servers under the User DSNs in the ODBC administrator (ex. one for nwisaz and one for nwisco) but you may not be able to access them unless your username is added to the read/write access list for each individual NWIS database. I just talked to one of the LDMs for nwisco and they're working on adding you. After you're given access add nwisco and test the connection in the OBDC administrator before starting WQReview.

**Comment by ehermosillo** [comment]
Thank you, Colin!

Edyth Hermosillo
U.S. Geological Survey
520 N. Park Ave, Suite 221
Tucson, AZ 85719
Office: (520) 670-3334
Cell: (928) 246-1509
><(((º> ~~~ ><(((º> ~~~ ><(((º>
