### ISSUE TITLE
Missing nitrate (00618) from data pull

### ISSUE THREAD

**Issue by kbeisner2** [USGS-R/WQ-Review#184]
I am pulling data tables for an upcoming report and noticed that nitrate as N (pcode 00618) is not included in the WQ review data tables.  Is there a reason that is missing or could it be added?  Thanks!

**Comment by cpenn-usgs** [comment]
Hi @kbeisner2, Pcode 00618 is a calculated parameter and WQReview only pulls parameters that are stored in the NWIS database. You will need to pull P00631 (NO2+NO3 as N) and P00613 (NO2 as N) and subtract them. Or use QWDATA or NWIS web, which will calculate P00618 when requested as part of a data pull.
