### ISSUE TITLE
readNWISodbc to pull uv data?

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/WQ-Review#70]
From a `dataRetrieval` user:
"One other way to do this might be to have the ability to pull data from the internal USGS database similar to that used in the new WQreview package.  However, in this case, I would need to pull uv data for discharge.
"
I _think_ I've updated the `importRDB1` function to handle standard ADAPS uv rdb output, but haven't done extensive testing. I don't want to have any database connections to dataRetrieval, but this might be a pretty straightforward enhancement to add to `WQ-Review`....maybe...

**Comment by tjmills** [comment]
I have thought about this already for writing a R package to handle Index-velocity ratings for the hydroacustics surface water folks as an add-on so to speak to Aquarius.

I need to talk to someone who knows about connecting to ADAPS

**Comment by dhdupre** [comment]
For what it's worth...
As short lived as ADAPS will be, making use of nwts2rdb is the trick.
When the qwdischarge program was built, the logic was designed that interrogates adaps in a looped fashion via nwts2rdb and then selects the "best" DV or UV to present to the user. There are times when one doesn't simply want the entire string of stored uv's.

The replacement to nwts2rdb for Aquarius is under development as I write...
