### ISSUE TITLE
Importing Lab Site Data and Blank table Issues-- fail to import and view data, download attempt leads to fatal error

### ISSUE THREAD

**Issue by jsolder-usgs** [USGS-R/WQ-Review#72]
For importing data, when trying to import the single site (404305111570501, UTWSC Lab) error message is "No samples exist in your local NWIS database site number specified, check data criteria".
When I add an additional site, the data imports fine.

In the blank table tab, the GUI balks when trying to view data for certain sites, throws error message "all vectors must be atomic, or data frames".  Here is message form R Studio "Error in list_to_dataframe(res, attr(.data, "split_labels"), .id, id_as_factor) : 
  Results must be all atomic, or all data frames"
After I view another site with blank information, the first site that had presented issues can now be viewed. 
After viewing data, I attempt to download the table which leads to a fatal error, forcing the R session to restart.

Attached is the site data. 

[saveData_UT_QWReviewFail.zip](https://github.com/USGS-R/WQ-Review/files/81697/saveData_UT_QWReviewFail.zip)

**Comment by tjmills** [comment]
Thank you for reporting this on GitHub!

The site 402709111525201 has no blank information, which may be causing the error. Although I do not get the error message when I attempt to display a blank table.

Also, when I look at the data it appears there is a) only one sample for site 402709111525201 and b) all samples for site 404305111570501 are OAQ. Does this sound correct to you?

**Comment by tjmills** [comment]
I also have no issue downloading the data table. Are you running the app in google chrome, or is it launching in an rstudio window?

**Comment by jsolder-usgs** [comment]
Yes, 402709111525201 was only loaded in so that I could get the data I
wanted into the .zip. I am not having issues with that site.

404305111570501 are only OAQ, it is the Lab here in Utah.

Hmm, yes it is running in Chrome.
I just tried again to download the table.
New tab opens:
http://127.0.0.1:4682/session/06e0ed1b45af54a860b08d7b3a13fc10/download/blankTableOut?w=

with this text: Results must be all atomic, or all data frames

On Thu, Jan 7, 2016 at 1:42 PM, T. Joe Mills notifications@github.com
wrote:

> Thank you for reporting this on GitHub!
> 
> The site 402709111525201 has no blank information, which may be causing
> the error. Although I do not get the error message when I attempt to
> display a blank table.
> 
> Also, when I look at the data it appears there is a) only one sample for
> site 402709111525201 and b) all samples for site 404305111570501 are OAQ.
> Does this sound correct to you?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGS-R/WQ-Review/issues/72#issuecomment-169799190.

## 

```
John E. Solder
Utah Water Science Center
U.S. Geological Survey
(801)908-5044
jsolder@usgs.gov
```

**Comment by tjmills** [comment]
Bizarre, I am having no issue with your data. I am updating my R and R studio to see if its a version issue.

**Comment by jsolder-usgs** [comment]
I'm running

R version 3.1.3 (2015-03-09) -- "Smooth Sidewalk"

RStudio Version 0.98.507

On Thu, Jan 7, 2016 at 1:56 PM, T. Joe Mills notifications@github.com
wrote:

> Bizarre, I am having no issue with your data. I am updating my R and R
> studio to see if its a version issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGS-R/WQ-Review/issues/72#issuecomment-169802698.

## 

```
John E. Solder
Utah Water Science Center
U.S. Geological Survey
(801)908-5044
jsolder@usgs.gov
```

**Comment by tjmills** [comment]
Yeah I did not think that would be the issue, that is the version I was on, and updating R to the most recent did not matter.

I will continue to look into it. Would you mind sending me your data one more time so I can be sure we have the same dataset?

I think I will need to get access to all NWIS databases for future troubleshooting, since the local server thing makes troubleshooting difficult.

**Comment by tjmills** [comment]
Also, regarding your original post...

> For importing data, when trying to import the single site (404305111570501, UTWSC Lab) error message is "No samples exist in your local NWIS database site number specified, check data criteria".
> When I add an additional site, the data imports fine.

This is because the first site only has OAQ data and no data in DB1, which is where it checks first and quits if there are no environmental samples. I will add this to the bug list and get it fixed.

**Comment by jsolder-usgs** [comment]
Thanks Joe.

In this case the number of detects are small, so I can transcribe, but
figured you would like to know about the bug.

On Thu, Jan 7, 2016 at 2:06 PM, T. Joe Mills notifications@github.com
wrote:

> Yeah I did not think that would be the issue, that is the version I was
> on, and updating R to the most recent did not matter.
> 
> I will continue to look into it. Would you mind sending me your data one
> more time so I can be sure we have the same dataset?
> 
> I think I will need to get access to all NWIS databases for future
> troubleshooting, since the local server thing makes troubleshooting
> difficult.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGS-R/WQ-Review/issues/72#issuecomment-169805106.

## 

```
John E. Solder
Utah Water Science Center
U.S. Geological Survey
(801)908-5044
jsolder@usgs.gov
```

**Comment by tjmills** [comment]
Absolutely I do, I will try and figure it out. Its odd that it is not occurring on my machine with your data, frustrating...
