### ISSUE TITLE
Pulling Streamgages from Nearby Sites

### ISSUE THREAD

**Issue by paxsoch** [USGS-R/WQ-Review#85]
I'm trying to reference in discharge data near several sites where we collect discrete samples.  However, there are no discrete samples at the discharge site.  When I try to plot the discharge with the discrete samples, the hydrograph doesn't show up.  Is there a way to fix this?

**Comment by tjmills** [comment]
If there are no discrete samples then discharge will not be pulled in because the Q values are only those stored in the discrete water-quality samples database, not continuous data. 

On my to-do list is to bring in the continuous data, but currently that is on hold
