### ISSUE TITLE
Table issues?

### ISSUE THREAD

**Issue by mdpetkew** [USGS-R/WQ-Review#93]
When pulling Replicate and Fil vs. Unf tables, I see the same sample repeated multiple (2 to 4) times.  Everything is the same for the two (to four) rows of data.  Is anyone else seeing this?

**Comment by tjmills** [comment]
Hi,

Yes this is an ongoing "issue" that I am not sure exactly how to deal with. There is a difference between the data somwhere, probably in a sample comment. Can you send me the data using the "save/load" tab in the GUI, or export it if using R?

**Comment by tjmills** [comment]
This can be fixed for tables where comments are not shown, such as the QAQC tables. I iwll fix using unique(). This will be updated in the next release

**Comment by tjmills** [comment]
Done

**Comment by mdpetkew** [comment]
Joe - just checking, so are you saying that it will be fixed for QAQC
tables, but can't be corrected for the data tables (wide and long)?  Do you
think this a WQ-Review issue or a NWIS issue?  I see the differences are
that lats, longs, and HUC codes are listed for one set of data and not the
other set of data.  All other data are equal for both sets.

Thanks for any information.

Matt

On Mon, Feb 8, 2016 at 11:00 AM, T. Joe Mills notifications@github.com
wrote:

> This can be fixed for tables where comments are not shown, such as the
> QAQC tables. I iwll fix using unique(). This will be updated in the next
> release
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGS-R/WQ-Review/issues/93#issuecomment-181419282.

## 

---

Matthew D. Petkewich
U.S. Geological Survey
Stephenson Center, Suite 129
720 Gracern Road
Columbia, SC 29210

803-750-6171 (office)
803-727-9041 (cell)

## 803-750-6181 (fax)

**Comment by tjmills** [comment]
Yes I am saying that it will be fixed in the QAQC tables. This is not exactly an NWIS "issue" its just that when you combine multiple tables from NWIS, some tables, like the comments, may have multiple values for the same result. 

I will look into it some more and see if there is a different way to join the tables to combine the information
