### ISSUE TITLE
'SITE_NO' not found when running flagReport.R

### ISSUE THREAD

**Issue by jlwilson-usgs** [USGS-R/WQ-Review#95]
Joe, 
I am revisiting the issue I had with a couple months ago. 

I am trying to use your flagReport script to create a series of trips (folders) with a series of sites in each trip so we can put it on an internal page. 

When I try to execute my script ([flagreport_AWQMN.txt](https://github.com/USGS-R/WQ-Review/files/128225/flagreport_AWQMN.txt)) I am getting the following error:
Quitting from lines 16-24 (networkSummary.rmd) 

Error in match(x, table, nomatch = 0L) : object 'SITE_NO' not found
In addition: Warning messages:
1: In dir.create(outputDir) :
  'C:\User_Files\Programs\R-3.2.3\AWQMN\Output' already exists
2: In left_join_impl(x, y, by$x, by$y) :
  joining factor and character vector, coercing into character vector
3: In value[[3L]](cond) :
  simpleWarning in left_join_impl(x, y, by$x, by$y): joining factor and character vector, coercing into character vector
This caused a warning DO NOT REPORT UNLESS YOU NOTICE A PROBLEM WITH PERFORMANCE
4: In readLines(input, encoding = "UTF-8") :
  incomplete final line found on '_output.yaml'
5: In readLines(input, encoding = "UTF-8") :
  incomplete final line found on '_output.yaml'
6: In fix_options(params) :
  You must not set both chunk options out.width and fig.retina

Like you said, this is a Rmarkdown error that is masking the real issue. 

You had thought that it was a memory issue, but I am running this on a new workstation with 32GB of memory and I am using your most recent flagReport script that uses dplyr.

Any thoughts what else it could be?

**Comment by tjmills** [comment]
Hi,

This is not a memory issue, it looks like a data import issue. In your output directory, AWQMN\Output, do you have a file called "data.rda"?

If so, can you email me it? I am in the process of getting access to state databases so that I can help troubleshoot, but it does not appear that I have access to NWISMO yet.

**Comment by tjmills** [comment]
OK, that issue is fixed. I am updating to git now. The problem was that some of the automated checks had no flags present and so the table was NULL and SITE_NO did not exist.

**Comment by tjmills** [comment]
You can install the new development version with 

``` r
library(devtools)
install_github("tmills-usgs/WQ-Review")
```

**Comment by jlwilson-usgs** [comment]
I am now getting the error:
Error in subset.default(reports$chemFlagTable, SITE_NO == site) : 
  object 'SITE_NO' not found

**Comment by tjmills** [comment]
Can you give me the call stack, like you did with the other error?

**Comment by jlwilson-usgs** [comment]
Yeah. Sorry. 

Quitting from lines 15-23 (flagReport.rmd) 

Error in subset.default(reports$chemFlagTable, SITE_NO == site) : 
  object 'SITE_NO' not found
In addition: Warning messages:
1: In readLines(input, encoding = "UTF-8") :
  incomplete final line found on '_output.yaml'
2: In fix_options(params) :
  You must not set both chunk options out.width and fig.retina
3: In as.POSIXlt.POSIXct(x, tz) : unknown timezone '
'
4: In fix_options(params) :
  You must not set both chunk options out.width and fig.retina
5: In fix_options(params) :
  You must not set both chunk options out.width and fig.retina
6: In fix_options(params) :
  You must not set both chunk options out.width and fig.retina
7: In fix_options(params) :
  You must not set both chunk options out.width and fig.retina
8: In readLines(input, encoding = "UTF-8") :
  incomplete final line found on '_output.yaml'
9: In fix_options(params) :
  You must not set both chunk options out.width and fig.retina

**Comment by tjmills** [comment]
ok got it fixed, same issue different place. This is kind of pervasive so if this last update does not fix it I will have to do a bigger change on Monday

**Comment by tjmills** [comment]
@jlwilson Is this working for you now?

**Comment by jlwilson-usgs** [comment]
Yeah, works great.

Thanks, Joe!

Sent from my iPhone

## 

Jordan L. Wilson, PE
Hydrologist
U.S. Geological Survey
Missouri Water Science Center
1400 Independence Road, MS 100 x-apple-data-detectors://6/1
Rolla, MO 65401 x-apple-data-detectors://6/1
Phone: 573-308-3539
Fax: 573.308.3645
email: jlwilson@usgs.gov

On Feb 15, 2016, at 9:56 AM, T. Joe Mills notifications@github.com wrote:

@jlwilson https://github.com/jlwilson Is this working for you now?
