### ISSUE TITLE
Filtered vs unfiltered

### ISSUE THREAD

**Issue by psolberg-usgs** [USGS-R/WQ-Review#97]
I suggest changing this to 'whole vs part'. This would allow comparison of such constituents as NO2 (part) to NO3 + NO2 (whole), orthop (part) to phosphorus (whole), as well as filtered & unfiltered analysis. I have attached a SAS output that has both parts / wholes and filtered & unfiltered comparisons. 

[whole2yr09081000.pdf](https://github.com/USGS-R/WQ-Review/files/135238/whole2yr09081000.pdf)

**Comment by tjmills** [comment]
I originally had this in but it got messy when there were multiple parts that were below detection being summed to a whole. It was messy both in that the algorithm was difficult to write, and that its usefulness when considering detection limits was debatable. 

I will revisit
