### ISSUE TITLE
Option to add 'minor gridlines'

### ISSUE THREAD

**Issue by psolberg-usgs** [USGS-R/WQ-Review#98]
I was eyeballing some values on a parameter vs parameter plot because I used a lab SC instead of fld SC for a sample, and desired the option to add one more set of gridlines so I could more easily eyeball the value, as it would lay on the constituent vs sc plot. (The reason I didn't plot lab SC vs constituent is because I only have 2 such samples, whereas fld SC vs constituent I have many many samples with a good r2 value, in case you were wondering).

**Comment by tjmills** [comment]
As long as it does not clutter the plots I can add that to all plots. It would not be a toggleable option though, just always on. 

Since these plots are for doing what your talking about and not for presentation I think that should be fine. I will take a look
